/**
 * Canonical fallback list of persona slugs.
 * Seeded from Dustin's pasted registry list.
 *
 * Used when /api/roles is unavailable or returns no usable options.
 */

export const CANON_AGENT_SLUGS: string[] = [
  // Dream Team (56)
  "agent_aegis",
  "agent_amani",
  "agent_app_dev_guru",
  "agent_app_development_guru",
  "agent_archivist",
  "agent_atlas",
  "agent_avery_marlowe",
  "agent_beacon",
  "agent_boost",
  "agent_bridge",
  "agent_chiesan",
  "agent_coda",
  "agent_codeblock",
  "agent_compass",
  "agent_conductor",
  "agent_dr_rowan_vagus",
  "agent_dr_somnus_hale",
  "agent_echo",
  "agent_editorial_approvals_lead",
  "agent_english_lyricist",
  "agent_english_poet",
  "agent_evidence_curator",
  "agent_forge",
  "agent_foundry",
  "agent_harbor",
  "agent_helm",
  "agent_ip_paralegal_docketing",
  "agent_izumi",
  "agent_izumi_takahashi",
  "agent_kaoru",
  "agent_kaoru_arai",
  "agent_ledger",
  "agent_lens",
  "agent_lexicode",
  "agent_lume",
  "agent_muse",
  "agent_navi",
  "agent_nest",
  "agent_nova",
  "agent_os",
  "agent_praetor",
  "agent_prism",
  "agent_pulse",
  "agent_relief",
  "agent_river",
  "agent_scout",
  "agent_sentinel",
  "agent_shield",
  "agent_sparkster",
  "agent_storybloom",
  "agent_stratega",
  "agent_tally",
  "agent_technical_claims_co_author",
  "agent_uplift",
  "agent_verifier",
  "agent_walt",

  // Pod Roles (42)
  "agent_3pl_integration_owner",
  "agent_accessibility_lead",
  "agent_analyst",
  "agent_author_platform_producer",
  "agent_billing_engineer",
  "agent_captioning_producer",
  "agent_channel_integrations_lead",
  "agent_cohort_ops_lead",
  "agent_contracts_desk",
  "agent_data_steward",
  "agent_distro_ops",
  "agent_education_programs_manager",
  "agent_governance_designer",
  "agent_ip_paralegal",
  "agent_packaging_pre_press_lead",
  "agent_partner_ops",
  "agent_patent_illustrator",
  "agent_patent_search_specialist",
  "agent_policy_librarian",
  "agent_returns_kitting_coordinator",
  "agent_rights_admin",
  "agent_security_reviewer",
  "agent_tenant_billing_pm",
  "agent_vendor_qa",
  "agentic_ai_master",
  "cost_controller",
  "data_curator",
  "evaluation_architect",
  "experiment_designer",
  "master_agentic_ai_advancement_officer",
  "master_agentic_ai_strategist",
  "memory_architect",
  "prompt_policy_systems_engineer",
  "reliability_sre_agentops",
  "safety_red_team_lead",
  "telemetry_tracing_lead",
  "tooling_steward",

  // Council (2)
  "agent_advisory_council_liaison",
  "agent_religious_scholar_council",

  // System Capability (1)
  "agent_agent_mode",
];

export function canonAgentsAsOptions() {
  return CANON_AGENT_SLUGS.map((slug) => ({ slug, label: slug }));
}
