import type { Request, Response } from "express";
import express from "express";
export const router = express.Router();

// Example: fetch coverage summary from a JSON file generated by your test runner
router.get("/api/coverage/summary", async (req: Request, res: Response) => {
  // In a real setup, read from coverage/coverage-summary.json
  res.json({ files: 42, lines: 12345, covered: 10234, pct: (10234/12345)*100 });
});
