import React, { useEffect, useMemo, useState } from 'react'
import { listRoles, listAgentSpecs, upsertAgentSpec } from '../lib/admin_ex'
import { diffRoleAgent, roleToSuggestedAgent } from '../lib/diff'
export default function RoleAgentSync(){
  const [roles,setRoles]=useState<any[]>([]); const [specs,setSpecs]=useState<any[]>([]); const [loading,setLoading]=useState(false); const [status,setStatus]=useState('')
  async function refresh(){ setLoading(true); try{ const [rs,as]=await Promise.all([listRoles(),listAgentSpecs()]); setRoles(rs||[]); setSpecs(as||[]) } finally { setLoading(false) } }
  useEffect(()=>{ refresh() }, [])
  const specsByHandle=useMemo(()=>{ const m:any={}; for(const s of specs){ m[s.handle]=s } return m },[specs])
  const unmapped=useMemo(()=> roles.filter((r:any)=>!specsByHandle[r.handle]), [roles,specsByHandle])
  const bulkGenerate=async()=>{ if(!unmapped.length){ alert('No missing Agent Specs.'); return } setLoading(true); setStatus('Generating specs...'); try{ for(const r of unmapped){ await upsertAgentSpec(roleToSuggestedAgent(r)) } setStatus('Generated '+unmapped.length+' specs.'); await refresh() } catch(e:any){ alert('Error generating specs: '+(e?.message||e)) } finally{ setLoading(false) } }
  const diffs=useMemo(()=> roles.map(r=>({handle:r.handle,title:r.title,diffs:diffRoleAgent(r,specsByHandle[r.handle])})), [roles,specsByHandle])
  const applySuggestion=async(handle:string,field:string,suggestion:any)=>{ try{ const spec=specsByHandle[handle]||roleToSuggestedAgent(roles.find((r:any)=>r.handle===handle)!); const updated={...spec} as any; updated[field]=suggestion; await upsertAgentSpec(updated); await refresh() } catch(e:any){ alert('Apply failed: '+(e?.message||String(e))) } }
  return (<section className="section"><h2>Roles ↔ Agent Specs — Bulk Map & Sync</h2><div style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'center'}}><button className="btn" data-pod="product" onClick={bulkGenerate} disabled={loading}>{loading?'Working…':`Generate Missing Specs (${unmapped.length})`}</button><button className="btn btn--secondary" onClick={refresh} disabled={loading}>Refresh</button>{status?<span className="chip">{status}</span>:null}</div><h3 style={{marginTop:16}}>Diffs (by handle)</h3><div style={{display:'grid',gap:10}}>{diffs.map((row:any,i:number)=>(<div key={row.handle+i} className="card"><div className="rail"/><div className="inner"><div className="title">{row.handle} — {row.title}</div>{row.diffs.length===0?(<p className="oneliner">No diffs — in sync ✅</p>):(<ul style={{margin:'8px 0 0 18px'}}>{row.diffs.map((d:any,idx:number)=>(<li key={idx}><b>{d.field}</b>: role=<code>{formatValue(d.roleValue)}</code> vs agent=<code>{formatValue(d.agentValue)}</code>{typeof d.suggestion!=='undefined'?(<button className="btn btn--secondary btn--sm" style={{marginLeft:8}} onClick={()=>applySuggestion(row.handle,d.field,d.suggestion)}>Apply suggestion</button>):null}</li>))}</ul>)}</div></div>))}</div></section>)
}
function formatValue(v:any){ if(Array.isArray(v)) return v.join(' | '); if(typeof v==='object' && v!==null) return JSON.stringify(v); return String(v ?? '') }
