name: Agent Lab — Weekly KPI Bot

on:
  schedule:
    - cron: '0 15 * * 1' # Mondays 08:00 Phoenix ~ 15:00 UTC
  workflow_dispatch:

jobs:
  kpi-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Summarize KPIs + WIP from labels
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            function readCSV(p){
              if (!fs.existsSync(p)) return null;
              const text = fs.readFileSync(p, 'utf-8').trim();
              const [head, ...rows] = text.split(/\r?\n/);
              const cols = head.split(',');
              return rows.map(r => {
                const vals = r.split(',');
                const o = {}; cols.forEach((c,i)=>o[c]=vals[i]); return o;
              });
            }
            // Governance CSV last row
            const gov = readCSV('DreamTeamHub/Agent-Lab/40_Playbooks/governance_metrics_weekly_template.csv') || [];
            const last = gov[gov.length-1] || {};

            // WIP and Promotion Board queue from labels: stage:* and stage:promotion-board
            const {owner, repo} = context.repo;
            const per_page = 100;
            async function listIssues(page){ 
              return (await github.rest.issues.listForRepo({owner, repo, state:'open', per_page, page})).data;
            }
            const all = [];
            for (let page=1; page<=5; page++){
              const data = await listIssues(page);
              all.push(...data);
              if (data.length < per_page) break;
            }
            const stageCounts = {ready:0, inprogress:0, review:0, promotion:0, deploywatch:0};
            all.forEach(i => {
              const labels = (i.labels||[]).map(l => (typeof l==='string'?l:l.name).toLowerCase());
              if (labels.includes('stage:ready')) stageCounts.ready++;
              if (labels.includes('stage:in-progress')) stageCounts.inprogress++;
              if (labels.includes('stage:review')) stageCounts.review++;
              if (labels.includes('stage:promotion-board')) stageCounts.promotion++;
              if (labels.includes('stage:deploy-watch')) stageCounts.deploywatch++;
            });

            const body = [
              `### Agent Lab — Weekly KPIs`,
              ``,
              `**Backlog:** ${last.backlog_size||'-'} • **Ready:** ${stageCounts.ready} • **In Progress:** ${stageCounts.inprogress} • **Review:** ${stageCounts.review} • **Promotion Board:** ${stageCounts.promotion} • **Deploy/Watch:** ${stageCounts.deploywatch}`,
              ``,
              `**Avg Lead (d):** ${last.avg_lead_days||'-'} • **Avg Cycle (d):** ${last.avg_cycle_days||'-'} • **SLA Breaches:** ${last.sla_breaches||'-'}`,
              ``,
              `**Post-Promotion Incidents:** ${last.post_promotion_incidents||'-'} • **Cost Variance %:** ${last.cost_variance_pct||'-'}`,
              ``,
              `${last.notes? ('Notes: ' + last.notes) : ''}`
            ].join('\n');

            await github.rest.issues.create({
              owner, repo, title: `Agent Lab — Weekly KPIs (${new Date().toISOString().slice(0,10)})`, body
            });
